// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace PeymanMq.Controllers
{
    public partial class ProductController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ProductController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ProductController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Select()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Select);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Details()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult InsertComment()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.InsertComment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult SelectProduct()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SelectProduct);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SelectRate()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SelectRate);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult InsertRate()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.InsertRate);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ProductController Actions { get { return MVC.Product; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Product";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Product";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Select = "Select";
            public readonly string Details = "Details";
            public readonly string InsertComment = "InsertComment";
            public readonly string SelectProduct = "SelectProduct";
            public readonly string Order = "Order";
            public readonly string SelectRate = "SelectRate";
            public readonly string InsertRate = "InsertRate";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Select = "Select";
            public const string Details = "Details";
            public const string InsertComment = "InsertComment";
            public const string SelectProduct = "SelectProduct";
            public const string Order = "Order";
            public const string SelectRate = "SelectRate";
            public const string InsertRate = "InsertRate";
        }


        static readonly ActionParamsClass_Select s_params_Select = new ActionParamsClass_Select();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Select SelectParams { get { return s_params_Select; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Select
        {
            public readonly string pageIndex = "pageIndex";
            public readonly string pageSize = "pageSize";
            public readonly string category = "category";
        }
        static readonly ActionParamsClass_Details s_params_Details = new ActionParamsClass_Details();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Details DetailsParams { get { return s_params_Details; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Details
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_InsertComment s_params_InsertComment = new ActionParamsClass_InsertComment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_InsertComment InsertCommentParams { get { return s_params_InsertComment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_InsertComment
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_SelectProduct s_params_SelectProduct = new ActionParamsClass_SelectProduct();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SelectProduct SelectProductParams { get { return s_params_SelectProduct; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SelectProduct
        {
            public readonly string itemID = "itemID";
            public readonly string categoryID = "categoryID";
        }
        static readonly ActionParamsClass_Order s_params_Order = new ActionParamsClass_Order();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Order OrderParams { get { return s_params_Order; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Order
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_SelectRate s_params_SelectRate = new ActionParamsClass_SelectRate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SelectRate SelectRateParams { get { return s_params_SelectRate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SelectRate
        {
            public readonly string itemID = "itemID";
        }
        static readonly ActionParamsClass_InsertRate s_params_InsertRate = new ActionParamsClass_InsertRate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_InsertRate InsertRateParams { get { return s_params_InsertRate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_InsertRate
        {
            public readonly string itemID = "itemID";
            public readonly string value = "value";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _PartialComment = "_PartialComment";
                public readonly string _PartialRandom = "_PartialRandom";
                public readonly string _PartialRating = "_PartialRating";
                public readonly string Details = "Details";
                public readonly string Index = "Index";
                public readonly string Order = "Order";
            }
            public readonly string _PartialComment = "~/Views/Product/_PartialComment.cshtml";
            public readonly string _PartialRandom = "~/Views/Product/_PartialRandom.cshtml";
            public readonly string _PartialRating = "~/Views/Product/_PartialRating.cshtml";
            public readonly string Details = "~/Views/Product/Details.cshtml";
            public readonly string Index = "~/Views/Product/Index.cshtml";
            public readonly string Order = "~/Views/Product/Order.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ProductController : PeymanMq.Controllers.ProductController
    {
        public T4MVC_ProductController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SelectOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int pageIndex, int pageSize, int? category);

        [NonAction]
        public override System.Web.Mvc.JsonResult Select(int pageIndex, int pageSize, int? category)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Select);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageIndex", pageIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageSize", pageSize);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "category", category);
            SelectOverride(callInfo, pageIndex, pageSize, category);
            return callInfo;
        }

        [NonAction]
        partial void DetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Details(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DetailsOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void InsertCommentOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, BLL.CommentProductInsertVM model);

        [NonAction]
        public override System.Web.Mvc.JsonResult InsertComment(BLL.CommentProductInsertVM model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.InsertComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            InsertCommentOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void SelectProductOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int itemID, int? categoryID);

        [NonAction]
        public override System.Web.Mvc.JsonResult SelectProduct(int itemID, int? categoryID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SelectProduct);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "itemID", itemID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "categoryID", categoryID);
            SelectProductOverride(callInfo, itemID, categoryID);
            return callInfo;
        }

        [NonAction]
        partial void OrderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Order()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Order);
            OrderOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void OrderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, BLL.OrderInsertVM model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Order(BLL.OrderInsertVM model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Order);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            OrderOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void SelectRateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int itemID);

        [NonAction]
        public override System.Web.Mvc.ActionResult SelectRate(int itemID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SelectRate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "itemID", itemID);
            SelectRateOverride(callInfo, itemID);
            return callInfo;
        }

        [NonAction]
        partial void InsertRateOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int itemID, byte value);

        [NonAction]
        public override System.Web.Mvc.JsonResult InsertRate(int itemID, byte value)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.InsertRate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "itemID", itemID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "value", value);
            InsertRateOverride(callInfo, itemID, value);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
